### PR TITLE
[artifact-manager] (#552) Implement exception handling during deletion of Custom Resource which is in use

### LINKED ISSUE #552: vRA Custom Resource push problem
### Discussed in https://github.com/vmware/build-tools-for-vmware-aria/discussions/550

<div type='discussions-op-text'>

<sup>Originally posted by **oporanski** December  2, 2024</sup>
Question 

I'm stuck with version 2.39.0. every time i try to upgrade vRBT and i try to run my pipeline i always get the error below.
It seems that vRA project try to delete existing Dynamic Type (Custom Resource). vRA do not allow to delete Custom Resource if any instances exist. The error you see is a try to push back the code to this same instance it was taken form!

Is this a issue with my pipeline or a known issue with vRBT? 
BTW is thee any build tools documentation and some more information what newer versions offer than what i can see in releases What's Changed If you are not a vRBT developer its not possible to understand this.

Error:
02:19:43.700 [main] INFO  com.vmware.pscoe.iac.artifact.store.vrang.VraNgCustomResourceStore - Importing custom resource BMS...
02:19:43.749 [main] INFO  com.vmware.pscoe.iac.artifact.store.vrang.VraNgCustomResourceStore - Custom resource 'BMS' already exists and has ID '3f691877-1bbb-4ac8-bbc1-acd2220b71c0'
02:19:43.750 [main] INFO  com.vmware.pscoe.iac.artifact.store.vrang.VraNgCustomResourceStore - Trying to delete custom resource 'BMS' first.
02:19:43.750 [main] INFO  com.vmware.pscoe.iac.artifact.rest.RestClientVraNg - Deleting custom resource with id '3f691877-1bbb-4ac8-bbc1-acd2220b71c0'
Exception in thread "main" java.lang.RuntimeException: Error executing POST to server: java.lang.RuntimeException : Could not delete custom resource with name 'BMS' (id:3f691877-1bbb-4ac8-bbc1-acd2220b71c0).
	at com.vmware.pscoe.iac.artifact.store.vrang.VraNgCustomResourceStore.importCustomResource(VraNgCustomResourceStore.java:316)
	at com.vmware.pscoe.iac.artifact.store.vrang.VraNgCustomResourceStore.importContent(VraNgCustomResourceStore.java:177)
	at com.vmware.pscoe.iac.artifact.VraNgPackageStore.importPackage(VraNgPackageStore.java:274)
	at com.vmware.pscoe.iac.artifact.VraNgPackageStore.importAllPackages(VraNgPackageStore.java:139)</div>

### PR DESCRIPTION
**Pull request by Michaelpalacce**
### Checklist

- [x] I have added relevant error handling and logging messages to help troubleshooting
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation, relevant usage information (if applicable)
- [x] I have updated the PR title with affected component, related issue number and a short summary of the changes introduced
- [x] I have added labels for implementation kind (kind/*) and version type (version/*)
- [x] I have tested against live environment, if applicable
- [x] I have synced any structure and/or content vRA-NG improvements with vra-ng and ts-vra-ng archetypes (if applicable)
- [x] I have my changes rebased and squashed to the minimal number of relevant commits. **Notice: don't squash all commits**
- [x] I have added a descriptive commit message with a short title, including a `Fixed #XXX -` or `Closed #XXX -` prefix to auto-close the issue

### Related issues and PRs

Closes #552

### CODE REVIEW

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/store/vrang/VraNgCustomResourceStore.java [hunk 1]
```diff
@@ -393,11 +393,10 @@ private static boolean isCustomResourceExistingInDifferentOrganization(
 		return (status == HttpStatus.BAD_REQUEST && message != null && message.indexOf(magicMessage) != -1);
 	}
 
-	private static boolean isCustomResourceActiveAttached(final HttpClientErrorException clientException) {
-		HttpStatus status = HttpStatus.valueOf(clientException.getStatusCode().value());
+	private static boolean isCustomResourceActiveAttached(final Exception clientException) {
 		final String magicMessage = "Resource type cannot be deleted as there are active resources attached to it";
 		String message = clientException.getMessage();
-		return (status == HttpStatus.BAD_REQUEST && message != null && message.indexOf(magicMessage) != -1);
+		return (message != null && message.indexOf(magicMessage) != -1);
```
Comment (akantchev) [inline common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/store/vrang/VraNgCustomResourceStore.java:399]: You can use `message.contains(magicMessage)`

Comment (Michaelpalacce) [reply common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/store/vrang/VraNgCustomResourceStore.java]: addressed

**Comment by Michaelpalacce** [comment]
Still need to test this if it's effective, looking for an environment

**Review by VenelinBakalov — APPROVED** [review]
