### PR TITLE
Fix #165, handle unsupported characters in legacy archetype workflow path

### LINKED ISSUE #165: vro:pull command for legacy archetype fails when workflow folder path name contains character &
### Description

When running a vro:pull command on legacy workflow archetype, if those workflows paths name contains the & character, the pull command will faill with the log below

### Steps to Reproduce

1. Have a vro package containing workflows which paths names (folder name) include the &
2. Try a vro:pull command of that package
3. See the maven vro:pull command fails

**Preconditions:** Have the "&" character in the workflow folder path name

**Expected behavior:** vRBT to handle this character as any other character and succeed

**Actual behavior:** It fails when running the vro:pull command

**Reproduces how often:** 100%

**Component/s:** maven/plugins/vropkg

**Affects Build/s:** 2.32.0

#### Client

-   Build Tools for VMware Aria Version: 2.32.0
-   Visual Studio Code Version:  1.70
-   OS Version: W10

#### Server

-   vRealize Automation Version: 8.11.1
-   vRealize Orchestrator Version: 8.11.1
-   vRealize Operations Version: n/a
-   vRealize Log Insight Version: n/a

### Failure Logs
```
[INFO] C:\Users\username\projects\windows_vra_catalog\legacy\workflows>node "C:\Users\username\projects\windows_vra_catalog\legacy\workflows\node_modules\@vmware-pscoe\vropkg\bin\\..\dist\cli.js" --in flat --srcPath C:\Users\LADM_T~1\AppData\Local\Temp\2\vro-xml-pull1906541284324290868\com.company.vrbt.winvra.legacy-1.0.0-SNAPSHOT.package --out tree --destPath C:\Users\username\projects\windows_vra_catalog\legacy\workflows --privateKeyPEM C:\.keystore\private_key.pem --certificatesPEM C:\.keystore\cert.pem --keyPass VMware1! --version 1.0.0-SNAPSHOT --packaging package --artifactId legacy --description "Build Tools for VMware Aria provides development and release management tools for implementing automation solutions                 based on the VMware Aria Suite and VMware Cloud Director. The solution enables Virtual Infrastructure Administrators and                  Automation Developers to use standard DevOps practices for managing and deploying content." --groupId com.company.vrbt.winvra
[INFO] info: Extracting package C:\Users\LADM_T~1\AppData\Local\Temp\2\vro-xml-pull1906541284324290868\com.company.vrbt.winvra.legacy-1.0.0-SNAPSHOT.package to "C:\Users\username\projects\windows_vra_catalog\legacy\workflows" folder...
[ERROR] C:\Users\username\projects\windows_vra_catalog\legacy\workflows\node_modules\@vmware-pscoe\vropkg\dist\serialize\tree.js:85
[ERROR]         : element.categoryPath.map(c => c.replace(/\./g, "/."));
[ERROR]                                           ^
[ERROR]
[ERROR] TypeError: Cannot read properties of undefined (reading 'replace')
[ERROR]     at C:\Users\username\projects\windows_vra_catalog\legacy\workflows\node_modules\@vmware-pscoe\vropkg\dist\serialize\tree.js:85:43
[ERROR]     at Array.map (<anonymous>)
[ERROR]     at C:\Users\username\projects\windows_vra_catalog\legacy\workflows\node_modules\@vmware-pscoe\vropkg\dist\serialize\tree.js:85:32
[ERROR]     at Generator.next (<anonymous>)
[ERROR]     at C:\Users\username\projects\windows_vra_catalog\legacy\workflows\node_modules\@vmware-pscoe\vropkg\dist\serialize\tree.js:8:71
[ERROR]     at new Promise (<anonymous>)
[ERROR]     at __awaiter (C:\Users\username\projects\windows_vra_catalog\legacy\workflows\node_modules\@vmware-pscoe\vropkg\dist\serialize\tree.js:4:12)
[ERROR]     at serializeTreeElement (C:\Users\username\projects\windows_vra_catalog\legacy\workflows\node_modules\@vmware-pscoe\vropkg\dist\serialize\tree.js:73:52)
[ERROR]     at C:\Users\username\projects\windows_vra_catalog\legacy\workflows\node_modules\@vmware-pscoe\vropkg\dist\serialize\tree.js:118:37
[ERROR]     at Array.forEach (<anonymous>)
[ERROR]     at Object.serializeTree (C:\Users\username\projects\windows_vra_catalog\legacy\workflows\node_modules\@vmware-pscoe\vropkg\dist\serialize\tree.js:118:18)
[ERROR]     at C:\Users\username\projects\windows_vra_catalog\legacy\workflows\node_modules\@vmware-pscoe\vropkg\dist\cli.js:124:24
[ERROR]     at Generator.next (<anonymous>)
[ERROR]     at fulfilled (C:\Users\username\projects\windows_vra_catalog\legacy\workflows\node_modules\@vmware-pscoe\vropkg\dist\cli.js:5:58)
[INFO] Running vropkg... finished
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for legacy-all 1.0.0-SNAPSHOT:
[INFO] 
[INFO] legacy.actions ..................................... SUCCESS [01:36 min]
[INFO] legacy ............................................. FAILURE [01:21 min]
[INFO] legacy-all ......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:36 min
[INFO] Finished at: 2023-09-05T15:27:42+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.vmware.pscoe.maven.plugins:o11n-xml-package-maven-plugin:2.35.0:pull (default-cli) on project legacy: Running vropkg... failed with code 1 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :legacy
```

### PR DESCRIPTION
**Pull request by sugeeshC**
### Description
Fix issue #165.  Resolved the build error that occurs when executing the 'vro:pull' command on the legacy workflow archetype due to special characters(&) in the workflow path. 

Pull process will be failed with descriptive error message for legacy archetype projects which contains special characters ('&') in workflow paths.

### Checklist

- [x] I have added relevant error handling and logging messages to help troubleshooting
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation, relevant usage information (if applicable)
- [x] I have updated CHANGELOG.md with a short summary of the changes introduced
- [ ] I have tested against live environment, if applicable
- [ ] I have synced any structure and/or content vRA-NG improvements with vra-ng and ts-vra-ng archetypes (if applicable)
- [ ] I have my changes rebased and squashed to the minimal number of relevant commits. **Notice: don't squash all commits**
- [x] I have added a descriptive commit message with a short title, including a `Fixed #XXX -` or `Closed #XXX -` prefix to auto-close the issue

### Release Notes

Fix 165 / vro:pull command for legacy archetype fails when workflow folder path name contains character '&'.

### Related issues and PRs

https://github.com/vmware/build-tools-for-vmware-aria/issues/165

### CODE REVIEW

File: typescript/vropkg/src/serialize/tree.ts [hunk 1]
```diff
@@ -100,7 +100,9 @@ const serializeTreeElement = async (context: any, element: t.VroNativeElement):
     } else {
         xInfo.ele("comment").cdata(complexActionComment(element));
     }
-
+    if (element?.categoryPath) {
+		element.categoryPath = element?.categoryPath.filter(x => x!=null);
```
Comment (akantchev) [inline typescript/vropkg/src/serialize/tree.ts:104]: Please use `!==` for checking for `null` as it is safer.

File: typescript/vropkg/src/parse/util.ts [hunk 2]
```diff
@@ -31,7 +31,12 @@ export const xmlToTag = (tags): string[] => tags.children.filter(e => e.attr &&
 export const stringToCategory = (category): string[] => category.split(/(?<!\/)\./)
     .map(path => { return path.replace(/\//g, "") })
     .filter(path => path != "");
-
+export const validateWorkflowPath = (xmlDocument) => {
+	const invalidElement = xmlDocument.children.find((e) => e.attr.name == null || e.attr.name =='undefined');
+	if (invalidElement && invalidElement.firstChild!=null){
+		console.warn(`Unsupported characters detected in the workflow path. The value "${invalidElement.firstChild.val}" contains characters that are not allowed. The folders with special characters will be ignored.`);
```
Comment (akantchev) [inline typescript/vropkg/src/parse/util.ts:37]: I think it would be better to throw an error in this case, as it would give the user a hint why the packaging / unwrapping did not succeed.

Comment (sugeeshC) [reply typescript/vropkg/src/parse/util.ts:37]: Thanks for the review. Initially, I throw an error in this case. But later found that with "JS vRO" type projects with similar case the folder is excluded and pull operation getting success. So to keep the system behavior consistent, we thought to add warning message in both cases and make pull operation success, excluding the special character folder.
Yes, we can go with throwing error on both types as well. WDYT @Michaelpalacce   ?

Comment (sugeeshC) [reply typescript/vropkg/src/parse/util.ts:37]: Further reflection, I've realized that my previous idea was misguided. Without throwing the error, the process of pulling and then pushing the project would miss the special character folder on the server. So the implementation added for throwing the error.

**Comment by Michaelpalacce** [comment]
@sugeeshC Lets resolve the conflicts and we can merge this. LGTM

**Review by Michaelpalacce — APPROVED** [review]

**Review by Michaelpalacce — APPROVED** [review]
LGTM
