### PR TITLE
fix vrealize:push fails for vCD 10.5, API version 38.0

### LINKED ISSUE #166: vrealize:push fails for vCD 10.5, API version 38.0
### Description

When using vCD 10.5 there is a breaking change affecting the way authentication works (described here: https://docs.vmware.com/en/VMware-Cloud-Director/10.5/rn/vmware-cloud-director-105-release-notes/index.html)

### Steps to Reproduce

1. execute mvn clean package vrealize:push -P<vcd10.5env>

**Preconditions:** Environment with vCD 10.5

**Expected behavior:** vcd extensibility plugin is published

**Actual behavior:** Error is thrown stating that method is not allowed

**Reproduces how often:** every time

**Component/s:** [ "common/artifact-manager" ]

**Affects Build/s:** [ 2.35.0 ]

#### Client

-   Build Tools for VMware Aria Version: 2.35.0

#### Server

-   vRealize Cloud Director Version: 10.5.0.22080047

### Failure Logs

`{
    "minorErrorCode": "METHOD_NOT_ALLOWED",
    "message": "HTTP method not allowed",
    "stackTrace": "com.vmware.vcloud.api.rest.toolkit.exceptions.MethodNotAllowedRestApiException: HTTP method not allowed\n\tat com.vmware.vcloud.api.rest.providers.filters.RestApiRequestVersionCompatibilityFilter.filter(RestApiRequestVersionCompatibilityFilter.java:90)\n\tat org.apache.cxf.jaxrs.utils.JAXRSUtils.runContainerRequestFilters(JAXRSUtils.java:1918)\n\tat org.apache.cxf.jaxrs.interceptor.JAXRSInInterceptor.processRequest(JAXRSInInterceptor.java:206)\n\tat org.apache.cxf.jaxrs.interceptor.JAXRSInInterceptor.handleMessage(JAXRSInInterceptor.java:79)\n\tat org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)\n\tat org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)\n\tat org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265)\n\tat org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)\n\tat org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)\n\tat org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)\n\tat org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)\n\tat org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:304)\n\tat org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:217)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:665)\n\tat org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:279)\n\tat org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1419)\n\tat org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)\n\tat org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1665)\n\tat org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:352)\n\tat com.vmware.vcloud.api.framework.web.ExtensibilityFilter.doFilter(ExtensibilityFilter.java:159)\n\tat org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)\n\tat com.vmware.vcloud.security.filters.ValidityExceptionFilter.doFilterHttp(ValidityExceptionFilter.java:47)\n\tat com.vmware.vcloud.security.filters.HttpFilterBean.doFilter(HttpFilterBean.java:35)\n\tat org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)\n\tat com.vmware.vcloud.security.web.RestSessionFilter.doFilter(RestSessionFilter.java:235)\n\tat org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)\n\tat com.vmware.vcloud.security.web.CellLivenessCheckFilter.doFilter(CellLivenessCheckFilter.java:54)\n\tat org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)\n\tat com.vmware.vcloud.security.web.SecurityContextCleanerFilter.doFilter(SecurityContextCleanerFilter.java:32)\n\tat org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)\n\tat com.vmware.vcloud.api.rest.versioning.AcceptHeaderFilter.doFilter(AcceptHeaderFilter.java:78)\n\tat org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)\n\tat com.vmware.vcloud.security.filters.ConversationFilter$1.run(ConversationFilter.java:39)\n\tat com.vmware.vcloud.security.filters.ConversationFilter$1.run(ConversationFilter.java:37)\n\tat com.vmware.vcloud.common.persist.ConversationContextExecutor.execute(ConversationContextExecutor.java:67)\n\tat com.vmware.vcloud.security.filters.ConversationFilter.doFilter(ConversationFilter.java:45)\n\tat org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)\n\tat org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:225)\n\tat org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:190)\n\tat org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)\n\tat org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)\n\tat org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:210)\n\tat org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)\n\tat com.vmware.vcloud.common.web.deployment.impl.HostCheckerFilter.doFilter(HostCheckerFilter.java:107)\n\tat org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)\n\tat org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)\n\tat com.vmware.vcloud.common.web.deployment.impl.RequestDiagnosticFilter.doFilter(RequestDiagnosticFilter.java:143)\n\tat org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)\n\tat org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)\n\tat com.vmware.vcloud.common.web.deployment.impl.ConfigurableSniffyFilter.doFilter(ConfigurableSniffyFilter.java:48)\n\tat org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)\n\tat org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)\n\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131)\n\tat org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:578)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223)\n\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1570)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1384)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)\n\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)\n\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1543)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1306)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)\n\tat org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:192)\n\tat org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:51)\n\tat org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:141)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)\n\tat org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:822)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)\n\tat org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:301)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)\n\tat org.eclipse.jetty.server.Server.handle(Server.java:563)\n\tat org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505)\n\tat org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)\n\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)\n\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)\n\tat org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)\n\tat org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)\n\tat org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:558)\n\tat org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:379)\n\tat org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:146)\n\tat org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)\n\tat org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)\n\tat org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)\n\tat org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)\n\tat org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)\n\tat org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)\n\tat com.vmware.vcloud.common.threading.ExtendedJettyQueuedThreadPool$CleaningRunnable.run(ExtendedJettyQueuedThreadPool.java:58)\n\tat org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)\n\tat com.vmware.vcloud.common.threading.ExtendedJettyQueuedThreadPool$CleaningRunnable.run(ExtendedJettyQueuedThreadPool.java:58)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)\n\tat com.vmware.vcloud.common.threading.ExtendedJettyQueuedThreadPool.runJob(ExtendedJettyQueuedThreadPool.java:43)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)\n\tat java.base/java.lang.Thread.run(Thread.java:829)\n"
}`

### PR DESCRIPTION
**Pull request by vganevjb**
### Description
VMware Cloud Director 10.5 and later do not support the /api/sessions API login endpoint.

The /api/sessions API login endpoint is deprecated since VMware Cloud Director API version 33.0. For version 38.0 and later, the /api/sessions API login endpoint is no longer supported. You can use the VMware Cloud Director OpenAPI login endpoints to access VMware Cloud Director.
Service provider access to the system organization- POST cloudapi/1.0.0/sessions/provider
Tenant access to all other organizations apart from the system organization- POST cloudapi/1.0.0/sessions
As per the backward compatibility commitment of VMware Cloud Director, versions 37.2 and earlier continue to support the /api/sessions API login endpoint.

### Checklist
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added relevant error handling and logging messages to help troubleshooting
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have updated CHANGELOG.md with a short summary of the changes introduced
- [x] I have tested against live environment, if applicable
- [ ] I have added relevant usage information (As-built)
- [ ] Any structure and/or content vRA-NG improvements are synchronized with vra-ng and ts-vra-ng archetypes
- [ ] Every new or updated Installer property is documented in docs/archive/doc/markdown/use-bundle-installer.md
- [ ] Dependencies in pom.xml are up-to-date
- [x] My changes have been rebased and squashed to the minimal number of relevant commits
- [x] My changes have a descriptive commit message with a short title, including a `Fixed #XXX -` or `Closed #XXX -` prefix to auto-close the issue

### Related issues and PRs
Fixed #166

### CODE REVIEW

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/RestClientVcdBasicAuthInterceptor.java [hunk 1]
```diff
@@ -60,9 +60,9 @@ public class RestClientVcdBasicAuthInterceptor extends RestClientRequestIntercep
 	private MediaType contentType;
 
 	/**
-	 * session api path.
+	 * Provider session api path.
 	 */
-	private static final String URL_SESSION = "/api/sessions";
+	private static final String PROVIDER_URL_SESSION = "/cloudapi/1.0.0/sessions/provider";
```
Comment (akantchev) [inline common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/RestClientVcdBasicAuthInterceptor.java:66]: I'd suggest to make both the REST endpoint backward compatible with old API version, for example check the vCD API version and if it is >= 38.0 then use the PROVIDER_URL_SESSION  otherwise to use URL_SESSION

Comment (vganevjb) [reply common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/RestClientVcdBasicAuthInterceptor.java:66]: Thank you for your feedback.
According to the API documentation is available since API v33 - https://developer.vmware.com/apis/vmware-cloud-director/latest/cloudapi/1.0.0/sessions/provider/post/

From these docs we can see v33 is mapped to VCD 10, which is deprecated -> https://developer.vmware.com/docs/14143/vmware-cloud-director-api-programming-guide/

Should we support deprecated versions?

**Comment by VenelinBakalov** [comment]
Hi, @vganevjb . I see you updated CHANGELOG.md which is great. Could you updated Release.md as well?
Here is a sample: https://github.com/vmware/build-tools-for-vmware-aria/pull/190/files#diff-2758ec22240769ca24b53db71e3dc4dc4a7990dabed3bc38bf2ec4456d19f3a1

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/RestClientVcdBasicAuthInterceptor.java (hunk 1 above)
Comment (VenelinBakalov) [reply common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/RestClientVcdBasicAuthInterceptor.java:66]: I think @akantchev 's idea is to have support for backwards compatibility in case the user is running on an older vCD version which supports just the old api

Comment (vganevjb) [reply common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/RestClientVcdBasicAuthInterceptor.java:66]: I see the second link isn't working properly - I am attaching another one - https://docs.vmware.com/en/VMware-Cloud-Director/index.html
VCD API version <=34 is deprecated and not supported, and this change supports =>33

Comment (ivo-kotev) [reply common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/RestClientVcdBasicAuthInterceptor.java:66]: changing should be fine.  The old endpoint will be for very old VCD versions that are out of support for more than an year (10.1 (v34) EOL is 2022-04-09)

**Review by ivo-kotev — APPROVED** [review]

**Comment by Michaelpalacce** [comment]
@VenelinBakalov I'd say let's merge this

**Review by Michaelpalacce — APPROVED** [review]
lgtm

**Comment by VenelinBakalov** [comment]
@Michaelpalacce I've missed the notification for this..it seems now there are some merge conflicts
@vganevjb are you available for fixing them? 
If not, I will check them, they are only changelog / release md so nothing big

**Review by VenelinBakalov — APPROVED** [review]
