### PR TITLE
[artifact-manager,installer,maven] (#341) Add `vrealize:clean` mvn phase for `vra-ng` projects and a `clean` option for Installer

### LINKED ISSUE #341: `vrealize:clean` for Aria Automation (`vra-ng` archetype)
### Description

We have a goal `archetype:clean` that allows us to clean up specific archetypes and their resources in Aria.

Currently, this goal throws a `UnsupportedOperationException` and this is intentional as later on `UnsupportedOperationException` is caught and flagged as only a warning, so the build won't fail.

We want to add support to delete these resources with the following constraints:

- Only delete whatever is defined in the `content.yaml`
- If the filter is something like: `subscriptions: ` then **DO NOTHING. DO NOT** delete all resources! This should be **overwritable** by setting a new flag, up to the implementer.
- Some resources may not be deletable, like for example `Cloud Templates` that are in use by `Deployments`. This is ok, we should log a warning in these cases.
- Resource deletion should be ordered correctly so we can delete without issues
- The documentation needs to be enhanced on how this can be used.

### PR DESCRIPTION
**Pull request by Michaelpalacce**
### Description

Added capabilities to delete content from vra-ng.

Did not introduce a variable for "delete all" in case a flag is set as the task said, as that is way too dangerous.

### Checklist

- [x] I have added relevant error handling and logging messages to help troubleshooting
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation, relevant usage information (if applicable)
- [x] I have updated the PR title with affected component, related issue number and a short summary of the changes introduced
- [x] I have added labels for implementation kind (kind/*) and version type (version/*)
- [ ] I have tested against live environment, if applicable
- [x] I have synced any structure and/or content vRA-NG improvements with vra-ng and ts-vra-ng archetypes (if applicable)
- [x] I have my changes rebased and squashed to the minimal number of relevant commits. **Notice: don't squash all commits**
- [x] I have added a descriptive commit message with a short title, including a `Fixed #XXX -` or `Closed #XXX -` prefix to auto-close the issue

### Testing

TBD

### Release Notes

The `vrealize:clean` command now supports the `vra-ng` profile.

> [!WARNING] 
> It does NOT support regional resource deletion as those are expected to be refactored in the future.

Also a new flag is added to the installer `vrang_delete_content` that will default to `false` if not set. If this flag is set, the environment will be cleaned.
The installer will also prompt you if you want to delete the content if you select false to importing the content.

### Related issues and PRs

Closes #341

### CODE REVIEW

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/VraNgPackageStore.java [hunk 1]
```diff
@@ -324,6 +350,6 @@ protected final VraNgPackageContent getPackageContent(final Package pkg) {
 	@Override
 	protected final void deleteContent(final Content content, final boolean dryrun) {
 		throw new UnsupportedOperationException(
```
Comment (VenelinBakalov) [inline common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/VraNgPackageStore.java:352]: Just for my info, what is in general the purpose of this function and the expected diff from the deletePackage functions which now have implementation?

Comment (Michaelpalacce) [reply common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/VraNgPackageStore.java:352]: Deletion is package based, vro and vra had packages that you can import. Those packages have "content" in them that could be deleted partially.

`deleteContent` is a function that need to be implemented in every "PackageStore". Currently the "VRA", "VRO" and "VCD" have an implementation of it.

The function works when you want to delete "old" content only, or "new" without "old" (not 100% sure on this one, don't want to check, but it doesn't matter). It's meant to delete only a subset of the data as for example, when you are deleting the "old" package, it may still contain data from the "newest" package you want to keep.

**Comment by Michaelpalacce** [comment]
Who let this AI in here 🤣?

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/model/vrang/VraNgBlueprint.java [hunk 2]
```diff
@@ -67,4 +132,21 @@ public boolean equals(Object obj) {
...
+
+	/**
+	 * Using `id` should be enough here, as `id`s in Aria are unique. Adding more
+	 * details for extra uniquieness.
+	 *
+	 * @return the hashcode numerical repesentation of the object
+	 */
+	@Override
+	public int hashCode() {
+		return new HashCodeBuilder(PRIME_NUMBER_17, PRIME_NUMBER_31)
```
Comment (VenelinBakalov) [inline common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/model/vrang/VraNgBlueprint.java:144]: Just for my info, why 17 and 31?

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/RestClientVraNg.java [hunk 3]
```diff
@@ -705,6 +742,25 @@ public List<VraNgCatalogItem> getCatalogItemsForProject(final String project) {
...
+	 *
+	 * @param catalogItemId catalog item id
+	 */
+	public void deleteCatalogItem(final String catalogItemId) {
+		try {
+			logger.info("Deleting catalog item with id '{}'", catalogItemId);
+			ResponseEntity<String> res = this.deleteCatalogItemPrimitive(catalogItemId);
+
+			if (!res.getStatusCode().is2xxSuccessful()) {
+				logger.error("Failed to delete catalog item with id '{}'", catalogItemId);
```
Comment (VenelinBakalov) [inline common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/RestClientVraNg.java:756]: I am not sure if it is worth doing but in theory we can extract a function for general delete - try ( execute passed function like a call back ) catch ( throw error for the specific passed type)

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/model/vrang/VraNgBlueprint.java (hunk 2 above)
Comment (Michaelpalacce) [reply common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/model/vrang/VraNgBlueprint.java:144]: I needed 2 random prime numbers, 😄  It's completely random 😄

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/RestClientVraNg.java (hunk 3 above)
Comment (Michaelpalacce) [reply common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/RestClientVraNg.java:756]: I would do it, but I didn't get the idea 😄 can you add a bit more details? Or some pseudo code

**Review by VenelinBakalov — APPROVED** [review]

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/VraNgPackageStore.java (hunk 1 above)
Comment (Michaelpalacce) [reply common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/VraNgPackageStore.java:352]: deletePackage will delete the entire package with all of it's content, while deleteContent will delete a single resource from the package.. so One WF, or action or config element, etc

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/RestClientVraNg.java (hunk 3 above)
Comment (Michaelpalacce) [reply common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/RestClientVraNg.java:763]: I am scared to do this 😄 

Jokes aside, Java is OOP language, doesn't play well with functions...

image

Example ^^^ ....

Idk how to make it work

Comment (Michaelpalacce) [reply common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/RestClientVraNg.java:763]: The exception needs to be handled, even tho it will never happen as it's handled in the deleteItem..

Comment (VenelinBakalov) [reply common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/RestClientVraNg.java:763]: @joroaf any ideas on this one?

**Review by VenelinBakalov — APPROVED** [review]

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/VraNgPackageStore.java (hunk 1 above)
Comment (VenelinBakalov) [reply common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/VraNgPackageStore.java:352]: oh got it thanks

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/model/vrang/Identifiable.java [hunk 4]
```diff
@@ -0,0 +1,31 @@
+package com.vmware.pscoe.iac.artifact.model.vrang;
```
[the remark this answers is not in the document]
Comment (Michaelpalacce) [reply common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/model/vrang/Identifiable.java:1]: Done

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/model/vrang/VraNgSubscription.java [hunk 5]
```diff
@@ -14,30 +14,64 @@
...
 
+	/**
+	 * @return The JSON representation of the subscription.
+	 */
 	public String getJson() {
 		return this.json;
 	}
 
+	/**
+	 * Cjecks if the subscription is equal to another object.
```
[the remark this answers is not in the document]
Comment (Michaelpalacce) [reply common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/model/vrang/VraNgSubscription.java:81]: Done

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/store/vrang/AbstractVraNgDeleteStore.java [hunk 6]
```diff
@@ -0,0 +1,66 @@
...
+	/**
+	 * This will delete all of the approvalPolicies that are present in the
+	 * `content.yaml`.
+	 *
+	 * If the policy does not exist on the server, then nothing will happen.
+	 * 
+	 * TODO: Make it so no definition means delete everything if a flag is set
+	 */
+	public void deleteContent() {
+		Logger logger = LoggerFactory.getLogger(this.getClass());
```
[the remark this answers is not in the document]
Comment (Michaelpalacce) [reply common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/store/vrang/AbstractVraNgDeleteStore.java:32]: Linting rules... apparently I am hiding a value. I also believe it actually also failed.

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/store/vrang/AbstractVraNgDeleteStore.java [hunk 7]
```diff
@@ -0,0 +1,66 @@
...
+ * This product may include a number of subcomponents with separate copyright notices and license terms. Your use of these subcomponents is subject to the terms and conditions of the subcomponent's license, as noted in the LICENSE file.
+ * #L%
+ */
+
+import java.util.List;
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
+
+import com.vmware.pscoe.iac.artifact.model.vrang.Identifiable;
+
```
[the remark this answers is not in the document]
Comment (Michaelpalacce) [reply common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/store/vrang/AbstractVraNgDeleteStore.java:23]: Done

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/store/vrang/AbstractVraNgDeleteStore.java [hunk 8]
```diff
@@ -0,0 +1,66 @@
...
+		}
+	}
+
+	/**
+	 * Used to fetch the store's data from the package descriptor.
+	 *
+	 * @return list of items
+	 */
+	protected abstract List<String> getItemListFromDescriptor();
+
```
[the remark this answers is not in the document]
Comment (Michaelpalacce) [reply common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/store/vrang/AbstractVraNgDeleteStore.java:55]: Done

File: docs/versions/latest/Release.md [hunk 9]
```diff
@@ -26,6 +26,16 @@
 
 [//]: # (Improvements -> Bugfixes/hotfixes or general improvements)
 
+### *`vrealize:clean` support for vra-ng*
+
+The `vrealize:clean` command now supports the `vra-ng` profile.
+
+> [!WARNING] 
+> It does NOT support regional resource deletion as those are expected to be refactored in the future.
```
[the remark this answers is not in the document]
Comment (Michaelpalacce) [reply docs/versions/latest/Release.md:34]: Separate one I would say
