### PR TITLE
[polyglotpkg] (#388) Add node18 and node20 as polyglot runtimes

### LINKED ISSUE #388: Polyglot archetype - Cannot package nodejs apps with runtime greater than version 14 of nodejs
### Description
We're using Aria Orchestrator version 8.18 and try to implement a nodejs action through polyglot with the build tools version 2.41.1 to be able to have a small package with some specific nodejs dependencies in it (such as webdav). 

### Steps to Reproduce

1. I've first tried to package it letting all polyglot.json config by default but when I push the package into Aria Orchestrator, it doesn't work as it has a node:12 runtime (And this is deprecated. See [the documentation page] (https://docs.vmware.com/en/VMware-Aria-Automation/8.18/Using-Automation-Orchestrator/GUID-13E3704E-A325-4CB1-AF57-45FEBDBBD159.html) )
2. I've tries to force the runtime version by adding a custom environment and specifying the version of node (node:20) but it failed to package the solution because the action runtime specified is not yest supported 
image

**Preconditions:**
Create a polyglot project with maven using the polyglot-archetype for vro (See [doc](https://github.com/vmware/build-tools-for-vmware-aria/blob/main/docs/versions/latest/Components/Archetypes/Polyglot/General/New%20Project.md))

**Expected behavior:**
I should be able to package the solution with the new versions of nodejs's Aria Orchestrator runtime

**Actual behavior:**
Cannot package the solution for newer version of Aria Orcherstrator

**Reproduces how often:** [What percentage of the time does it reproduce]
100% of the time

**Component/s:**
typescript/polyglotpkg

**Affects Build/s:** [Which are the Build Tools for VMware Aria releases / builds affected by the issue]

#### Client
-   Build Tools for VMware Aria Version: 2.41.1
-   Visual Studio Code Version: 1.92.2
-   OS Version: /

#### Server
-   vRealize Automation Version: /
-   vRealize Orchestrator Version:  8.18.0.24015865
-   vRealize Operations Version: /
-   vRealize Log Insight Version: /

### Failure Logs
See the picture above in the step to reproduce

### Related issues and PRs
/

### Additional Context
/

### PR DESCRIPTION
**Pull request by Michaelpalacce**
### Description

The following runtimes have been added to the polyglot archetype:

- `node:18`
- `node:20`

### Checklist

- [x] I have added relevant error handling and logging messages to help troubleshooting
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation, relevant usage information (if applicable)
- [x] I have updated the PR title with affected component, related issue number and a short summary of the changes introduced
- [x] I have added labels for implementation kind (kind/*) and version type (version/*)
- [x] I have tested against live environment, if applicable
- [x] I have synced any structure and/or content vRA-NG improvements with vra-ng and ts-vra-ng archetypes (if applicable)
- [x] I have my changes rebased and squashed to the minimal number of relevant commits. **Notice: don't squash all commits**
- [x] I have added a descriptive commit message with a short title, including a `Fixed #XXX -` or `Closed #XXX -` prefix to auto-close the issue

### Testing

TBD

### Related issues and PRs

Closes #388

### CODE REVIEW

**Comment by Michaelpalacce** [comment]
I still need to test this... But it should work. If anyone can assist, that'd be great

**Comment by Michaelpalacce** [comment]
Label help-needed added for testers

File: typescript/polyglotpkg/src/lib/model.ts [hunk 1]
```diff
@@ -6,116 +6,156 @@
...
+	ActionRuntime.VRO_POWERCLI_11_PS_62,
+	ActionRuntime.VRO_POWERCLI_12_PS_71
+];
+
+export const VroPythonActionRuntimes = [
+	ActionRuntime.VRO_PYTHON_37,
+	ActionRuntime.VRO_PYTHON_310
+];
+
+export const NodeJsActionRuntimes = VroNodeJsActionRuntimes.concat(...[ActionRuntime.ABX_NODEJS]);
```
Comment (VenelinBakalov) [inline typescript/polyglotpkg/src/lib/model.ts:63]: Why do we need both spread and concat? Don't we need either
```` VroNodeJsActionRuntimes.concat(ActionRuntime.ABX_NODEJS) ```
or
``` [...VroNodeJsActionRuntimes, ActionRuntime.ABX_NODEJS]```

I might be wrong though...

File: typescript/polyglotpkg/src/lib/model.ts [hunk 2]
```diff
@@ -6,116 +6,156 @@
...
+ * Holds a list of ABX runtimes and their corresponding VRO runtimes.
+ * Used to replace VRO runtimes with ABX runtimes if abx project is detected.
+ */
+export const MappedAbxRuntimes = {
+	[ActionRuntime.ABX_NODEJS]: VroNodeJsActionRuntimes,
+	[ActionRuntime.ABX_POWERSHELL]: VroPowershellActionRuntimes,
+	[ActionRuntime.ABX_PYTHON]: VroPythonActionRuntimes
+};
+
+export type ActionRuntimeType = typeof NodeJsActionRuntimes[number] | typeof PowershellActionRuntimes[number] | typeof PythonActionRuntimes[number];
```
Comment (VenelinBakalov) [inline typescript/polyglotpkg/src/lib/model.ts:79]: How does this [number] syntax work? is it something like "Take the type of the array value at any index" or something?

File: typescript/polyglotpkg/src/lib/model.ts [hunk 3]
```diff
@@ -6,116 +6,156 @@
...
-        base?: string,
-        tags?: Array<string>
-        memoryLimitMb?: number,
-        timeoutSec?: number,
-        protocolType?: 'Ssl3' | 'Tls' | 'Tls11' | 'Tls12' | 'Tls13'
-    }
-}
+	platform: {
+		action: string,
+		entrypoint: string,
```
Comment (VenelinBakalov) [inline typescript/polyglotpkg/src/lib/model.ts:92]: Should we use ; anywhere on the export type instead of ,

File: typescript/polyglotpkg/src/lib/model.ts [hunk 4]
```diff
@@ -6,116 +6,156 @@
...
+		runtime: ActionRuntimeType,
+		base?: string,
+		tags?: Array<string>;
```
Comment (VenelinBakalov) [inline typescript/polyglotpkg/src/lib/model.ts:95]: Should we use ; anywhere on the export type instead of ,

File: typescript/polyglotpkg/src/lib/utils.ts [hunk 5]
```diff
@@ -3,77 +3,66 @@ import fs from 'fs-extra';
...
-            return pkg.vro ? ActionRuntime.VRO_POWERCLI_11_PS_62 : ActionRuntime.ABX_POWERSHELL;
-        case 'python:3.7':
-            return pkg.vro ? ActionRuntime.VRO_PYTHON_37 : ActionRuntime.ABX_PYTHON;
-        case 'python:3.10':
-        case 'python':
-            return pkg.vro ? ActionRuntime.VRO_PYTHON_310 : ActionRuntime.ABX_PYTHON;
-        default:
-            return pkg.platform.runtime;
-    }
+	for (const [key, value] of Object.entries(MappedAbxRuntimes)) {
```
Comment (VenelinBakalov) [inline typescript/polyglotpkg/src/lib/utils.ts:41]: Nice! Cool SOLID improvement :)

File: typescript/polyglotpkg/src/packager.ts [hunk 6]
```diff
@@ -11,84 +11,73 @@ import createLogger from './lib/logger';
...
+		/*-
+		 * #%L
+		 * polyglotpkg
+		 * %%
+		 * Copyright (C) 2023 - 2024 VMware
+		 * %%
+		 * Build Tools for VMware Aria
+		 * Copyright 2023 VMware, Inc.
+		 *
+		 * This product is licensed to you under the BSD-2 license (the "License"). You may not use this product except in compliance with the BSD-2 License.
```
Comment (VenelinBakalov) [inline typescript/polyglotpkg/src/packager.ts:34]: Love the licensing placement...this is the same issue that we discussed in here right?
https://github.com/vmware/build-tools-for-vmware-aria/issues/381

**Review by VenelinBakalov — APPROVED** [review]

**Review by VenelinBakalov — CHANGES_REQUESTED** [review]
Needs merge with latest state of main

File: typescript/polyglotpkg/src/lib/model.ts (hunk 1 above)
Comment (Michaelpalacce) [reply typescript/polyglotpkg/src/lib/model.ts:63]: Great catch, I think I was mind flooding myself :D

File: typescript/polyglotpkg/src/lib/model.ts (hunk 2 above)
Comment (Michaelpalacce) [reply typescript/polyglotpkg/src/lib/model.ts:79]: I think so... I was testing things out and this worked

File: typescript/polyglotpkg/src/lib/model.ts [hunk 7]
```diff
@@ -6,116 +6,156 @@
...
-    [key: string]: any,
-    name: string,
-    description: string,
-    version: string,
-    files?: Array<string>,
+	[key: string]: any,
+	name: string,
+	description: string,
+	version: string,
+	files?: Array<string>,
```
[the remark this answers is not in the document]
Comment (Michaelpalacce) [reply typescript/polyglotpkg/src/lib/model.ts:86]: I cleaned the file up from , and replaced them with ; where applicable

File: typescript/polyglotpkg/src/packager.ts (hunk 6 above)
Comment (Michaelpalacce) [reply typescript/polyglotpkg/src/packager.ts:34]: Yes... It's driving me insane... it also messes up my IDE whenever it happens...

**Comment by Michaelpalacce** [comment]
@VenelinBakalov I think I addressed everything

**Review by VenelinBakalov — APPROVED** [review]

**Review by VenelinBakalov — APPROVED** [review]
