### PR TITLE
[artifact-manager] [archetypes/vra] (#210) Cloud Template folder name and the name from details.json mismatch issue fixed in vRA

### LINKED ISSUE #210: Cloud Template folder name is used when validating if the record exists on the server, but the name in the details.json is used when creating/updating
### Description

Perhaps we can think of a structure where only one or the other is used as a source of truth. A good option would be to only use the folder name and add it to the details.json. 

It would be beneficial if we take a similar approach to other resources to unify the logic as much as possible?

### Alternatives

An alternative solution would be to use the details.json, however that will conflict with how the resources are exported.

### Additional Context

N/A

### PR DESCRIPTION
**Pull request by sugeeshC**
### Description

Cloud Template folder name and details.json->name mismatch issue fixed.

_Previous Behavior_ 

- When Cloud-Template folder name and details.json->name mismatch,  folder name is used for validating if the record exists on the server and details.json->name is used for creating/updating the cloud template on server.

_Current Behavior_

- When Cloud-Template folder name and details.json->name mismatch, now an error throwing explaining the mismatch.  

- details.json->name is now used for both validating and creating/updating cloud template on the server.

### Checklist

- [x] I have added relevant error handling and logging messages to help troubleshooting
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation, relevant usage information (if applicable)
- [x] I have updated the PR title with affected component, related issue number and a short summary of the changes introduced
- [x] I have added labels for implementation type (enhancement, bug, dependencies) and version change (major, minor, patch)
- [x] I have tested against live environment, if applicable
- [ ] I have synced any structure and/or content vRA-NG improvements with vra-ng and ts-vra-ng archetypes (if applicable)
- [ ] I have my changes rebased and squashed to the minimal number of relevant commits. **Notice: don't squash all commits**
- [x] I have added a descriptive commit message with a short title, including a `Fixed #XXX -` or `Closed #XXX -` prefix to auto-close the issue

### Testing

1.) Create vra 8 project using build-tools-for-vmware-aria.
2.) Create blueprint folder(Test-Blueprint-1) and content.yaml, details.json files accordingly.
3.) Add the blueprint folder name(Test-Blueprint-1) in project content.yaml.
4.) Change the details.json->name value into different from blueprint folder name. (Test-Blueprint-2)
5.) Push project to vra server.

### Release Notes

[artifact-manager] (#210) Cloud Template folder name and details.json->name mismatch issue fixed in vra.

### Related issues and PRs

Closed #210

### Additional Notes

Please note that, this fix is applying only when, we have a 'blueprint folder' named as in the project 'content.yaml'. 

Examples  

- Scenario 1 - Fix will be applied in this scenario.

#### content.yaml

```
blueprint:
  - Test-1
```

#### blueprints/Test-1/details.json

```json
{
  "name": "Test-2",
  "description": "",
  "requestScopeOrg": false
}
```

- Scenario 2 - Fix would not applied in following scenario. ( Since there is no 'Test-1' folder, blueprint will be skipped. )

#### content.yaml

```yml
blueprint:
  - Test-1

```

#### blueprints/Test-2/details.json

```json
{
  "name": "Test-1",
  "description": "",
  "requestScopeOrg": false
}
```

For the second scenario, this is the current behavior as well.

### CODE REVIEW

**Comment by sugeeshC** [comment]
Please note that, this fix is applying only when, we have a 'blueprint folder' named as in the project 'content.yaml'. 

eg -  

- scenario 1 - Fix will be applied in this scenario.

### content.yaml

```
blueprint:
  - Test-1
```


### blueprints/Test-1/details.json

```
{
  "name": "Test-2",
  "description": "",
  "requestScopeOrg": false
}
```


- scenario 2 - Fix would not applied in following scenario. ( Since there is no 'Test-1' folder, blueprint will be skipped. )

### content.yaml

```
blueprint:
  - Test-1

```

### blueprints/Test-2/details.json

```
{
  "name": "Test-1",
  "description": "",
  "requestScopeOrg": false
}
```

For the second scenario, this is the existing behavior as well.

**Review by akantchev — APPROVED** [review]

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/store/vrang/VraNgBlueprintStore.java [hunk 1]
```diff
@@ -241,10 +242,15 @@ private void handleBlueprintImport(final File bpDir, final Map<String, VraNgBlue
...
+		// Check the blueprint folder name(bpName) with details.json->name(bp.getName())
+		if (!Objects.equals(bp.getName(), bpName)) {
+			throw new IllegalStateException(String.format("Mismatch between blueprint folder name and details.json->name. (%s, %s)", bpName, bp.getName()));
+		}
+
 		// Check if the blueprint exists
 		VraNgBlueprint existingRecord = null;
-		if (bpsOnServerByName.containsKey(bpName)) {
-			existingRecord = bpsOnServerByName.get(bpName);
+		if (bpsOnServerByName.containsKey(bp.getName())) {
```
Comment (bcpmihail) [inline common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/store/vrang/VraNgBlueprintStore.java:252]: Is the change necessary? After all, we verify bp.getName() equals bpName above.

File: docs/versions/latest/Release.md [hunk 2]
```diff
@@ -190,6 +190,17 @@ The `enableConfigManager`, `maximumHardwareVersionKey` and `desiredSoftwareSpec`
 
 <https://github.com/vmware/build-tools-for-vmware-aria/issues/297>
 
+### Cloud Template folder name and details.json->name mismatch issue fixed
+
+#### Previous Behavior
+
+- When Cloud-Template folder name and details.json->name mismatch,  folder name is used for validating if the record exists on the server and details.json->name is used for creating/updating the cloud template on server.
```
Comment (bcpmihail) [inline docs/versions/latest/Release.md:197]: Use of '->' is confusing, please reword - e.g. 'When the Cloud-Template folder name does not match the name from details.json, ...'. Same for current behaviour and the comment in VraNgBlueprintStore.java (l.245)

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/store/vrang/VraNgBlueprintStore.java (hunk 1 above)
Comment (sugeeshC) [reply common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/store/vrang/VraNgBlueprintStore.java:252]: This will ensure the single source of truth for both validation and updating operations. It would be beneficial for future maintenance. If we later decide to remove the exception or do make  other changes on this code, having a consistent source will simplify the things.  WDYT?

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/store/vrang/VraNgBlueprintStore.java [hunk 3]
```diff
@@ -241,10 +242,15 @@ private void handleBlueprintImport(final File bpDir, final Map<String, VraNgBlue
 		VraNgBlueprint bp = loadBlueprintFromFilesystem(bpDir);
 		String bpID;
 
+		// Check the blueprint folder name(bpName) with the name from details.json(bp.getName())
```
Comment (Michaelpalacce) [inline common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/store/vrang/VraNgBlueprintStore.java:245]: We have a practice of adding way too many inline comments and not enough documentation to the methods 😄 let's change that

**Review by Michaelpalacce — CHANGES_REQUESTED** [review]

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/store/vrang/VraNgBlueprintStore.java [hunk 4]
```diff
@@ -241,10 +242,15 @@ private void handleBlueprintImport(final File bpDir, final Map<String, VraNgBlue
...
+		if (!Objects.equals(bp.getName(), bpName)) {
```
[the remark this answers is not in the document]
Comment (sugeeshC) [reply common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/store/vrang/VraNgBlueprintStore.java:246]: If it comes to bp.getName() = null (if in details.json -> "name": null), then it would make NullPointException. 
But instead of that we can use "!bpName.equals(bp.getName())" hoping that folder-name would never be null. 
But to be on the safe side, Objects.equals() might be best. WDYT?

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/store/vrang/VraNgBlueprintStore.java (hunk 3 above)
Comment (sugeeshC) [reply common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/store/vrang/VraNgBlueprintStore.java:245]: True, Not enough Doc comments. 😄
But I added this inline comment because it took me some time to identify the variables bpName and bp.getName() and understand what values they represent. With the comment, anyone can quickly see that bpName corresponds to the 'blueprint folder name' and bp.getName() corresponds to the 'name from details.json'. Idea was adding comment might make easy to understand the variables without tracing where the values are set. WDYT ? Should I remove it?

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/store/vrang/VraNgBlueprintStore.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (Michaelpalacce) [reply common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/store/vrang/VraNgBlueprintStore.java:246]: Ahh cool stuff! Ty

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/store/vrang/VraNgBlueprintStore.java (hunk 3 above)
Comment (Michaelpalacce) [reply common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/store/vrang/VraNgBlueprintStore.java:245]: Looks fine, keep it, but add to the documentation too

**Review by Michaelpalacce — APPROVED** [review]
