### PR TITLE
[artifact-manager) (#588) Policies import and export for multi tenant environments

### LINKED ISSUE #588: Policy imports to tenants on the same appliance don't work as expected
### Description

Exported policies (tested with day-2 policies) from one tenant cannot be imported in another on the same appliance using the build tools. 

### Steps to Reproduce

1. Create a new policy in tenant 1
2. Export Policy to codebase via content.yaml using vra-ng:pull
3. Push code to tenant 2

**Preconditions:**
Have multiple tenants on the same appliance (for this report tenant 1 & 2).

**Expected behavior:**
The policy should be imported into tenant 2 by the build tools.

**Actual behavior:**
The build tools say "attempting to import" but do not import into tenant 2.
Any changes made to the policy in the code get applied to the version in tenant 1.

**Reproduces how often:** 100%

**Component/s:**
Maven/plugins/vra-ng

**Affects Build/s:**
3.1.1

#### Client

- Build Tools for VMware Aria Version: 3.1.1
- vsCode Version: 1.96.2

#### Dependencies

Apache Maven 3.9.9
Node v22.9.0
Java version: 17.0.12

#### Server

- vRealize Automation Version: 8.18.1.36791
- vRealize Orchestrator Version: 8.18.1.36791

### Failure Logs

na

### PR DESCRIPTION
**Pull request by Michaelpalacce**
### Checklist

- [x] I have added relevant error handling and logging messages to help troubleshooting
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation, relevant usage information (if applicable)
- [x] I have updated the PR title with affected component, related issue number and a short summary of the changes introduced
- [x] I have added labels for implementation kind (kind/*) and version type (version/*)
- [x] I have tested against live environment, if applicable
- [x] I have synced any structure and/or content vRA-NG improvements with vra-ng and ts-vra-ng archetypes (if applicable)
- [x] I have my changes rebased and squashed to the minimal number of relevant commits. **Notice: don't squash all commits**
- [x] I have added a descriptive commit message with a short title, including a `Fixed #XXX -` or `Closed #XXX -` prefix to auto-close the issue

### Related issues and PRs

Closes #588

### CODE REVIEW

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgDeploymentLimitPolicyStore.java [hunk 1]
```diff
@@ -68,6 +89,14 @@ protected void deleteResourceById(String resId) {
 		this.restClient.deletePolicy(resId);
 	}
 
+	////////////////////////////////////////////////////
```
Comment (Tchoui) [inline common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgDeploymentLimitPolicyStore.java:92]: Redundant Comment

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgDeploymentLimitPolicyStore.java [hunk 2]
```diff
@@ -78,98 +107,76 @@ protected void deleteResourceById(String resId) {
...
+			this.logger.warn("Deployment Limit policy '{}' already exists on the server. Deleting it first.",
+					policy.getName());
+			this.deleteResourceById(policiesOnServer.get(policy.getName()).getId());
 		}
+
+		this.logger.info("Attempting to create deployment limit policy '{}'", policy.getName());
+		this.restClient.createDeploymentLimitPolicy(policy);
 	}
 
+	////////////////////////////////////////////////////
```
Comment (Tchoui) [inline common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgDeploymentLimitPolicyStore.java:166]: Redundant comment.

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgLeasePolicyStore.java [hunk 3]
```diff
@@ -54,96 +57,111 @@ protected List<VraNgLeasePolicy> getAllServerContents() {
...
+
+	////////////////////////////////////////////////////
+	// Delete
+	////////////////////////////////////////////////////
+
 	protected void deleteResourceById(String resId) {
 		this.restClient.deletePolicy(resId);
 	}
 
+	////////////////////////////////////////////////////
```
Comment (Tchoui) [inline common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgLeasePolicyStore.java:82]: Redundant comment.

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgLeasePolicyStore.java [hunk 4]
```diff
@@ -153,150 +171,90 @@ private VraNgLeasePolicy jsonFileToVraNgLeasePolicy(final File jsonFile) {
 		}
 	}
 
+	////////////////////////////////////////////////////
```
Comment (Tchoui) [inline common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgLeasePolicyStore.java:174]: Redundant comment.

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgResourceQuotaPolicyStore.java [hunk 5]
```diff
@@ -68,6 +89,14 @@ protected void deleteResourceById(String resId) {
 		this.restClient.deletePolicy(resId);
 	}
 
+	////////////////////////////////////////////////////
```
Comment (Tchoui) [inline common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgResourceQuotaPolicyStore.java:92]: Redundant comment.

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgResourceQuotaPolicyStore.java [hunk 6]
```diff
@@ -161,163 +182,90 @@ private VraNgResourceQuotaPolicy jsonFileToVraNgResourceQuotaPolicy(final File j
...
-	 */
-	@Override
-	protected List<String> getItemListFromDescriptor() {
-		if (this.vraNgPackageDescriptor.getPolicy() == null) {
-			return null;
-		} else {
-			return this.vraNgPackageDescriptor.getPolicy().getResourceQuota();
-		}
-	}
+	///////////////////////////////////////////
```
Comment (Tchoui) [inline common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgResourceQuotaPolicyStore.java:185]: Redundant comment.

**Review by Tchoui — APPROVED** [review]
LGTM.

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgApprovalPolicyStore.java [hunk 7]
```diff
@@ -73,6 +95,14 @@ protected void deleteResourceById(String resId) {
 		this.restClient.deletePolicy(resId);
 	}
 
+	///////////////////////////////////////////
```
[the remark this answers is not in the document]
Comment (Michaelpalacce) [reply common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgApprovalPolicyStore.java:98]: These are "blocks" aka starts from one and ends to the other. Helps me internalise things better.

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgContentSharingPolicyStore.java [hunk 8]
```diff
@@ -81,70 +102,93 @@ protected void deleteResourceById(String resId) {
...
 	/**
 	 * Exports all the content for the given project.
 	 */
 	@Override
 	protected void exportStoreContent() {
-		List<VraNgContentSharingPolicy> csPolicies = this.restClient.getContentSharingPolicies();
-		Path policyFolderPath = getPolicyFolderPath();
-
-		this.handleContentSharingPolicyExport(csPolicies, policyFolderPath);
+		this.exportStoreContent(new ArrayList<String>());
```
Comment (pboychev-bcom) [inline common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgContentSharingPolicyStore.java:191]: A question on these "empty" exports - if I understand correctly if there are none listed we export none, right?
Would it make sense to make this a bit more flexible and consider the following cases, configuration is:
- Missing - export all.
- An empty array - export none.
- Specific list - only export what is in the list.

Let me know if it makes sense and / or would like to discuss the idea further :)
It may be handled by the "exportStoreContent" method definition that accepts a list, if that's the case - ignore this comment :D

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgContentSharingPolicyStore.java [hunk 9]
```diff
@@ -155,48 +199,89 @@ protected void exportStoreContent() {
...
+			Gson gson = new GsonBuilder().setStrictness(Strictness.LENIENT).setPrettyPrinting().create();
+			String policyJson = gson.toJson(policy);
+
+			// write content sharing file
+			logger.info("Created content sharing file {}",
+					Files.write(Paths.get(policyFile.getPath()), policyJson.getBytes(),
+							StandardOpenOption.CREATE));
+		} catch (IOException e) {
+			throw new RuntimeException(
+					String.format(
```
Comment (pboychev-bcom) [inline common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgContentSharingPolicyStore.java:242]: Looks like we have two tabs indentation, there's a few other occurrences of this in the code here and there.

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgApprovalPolicyStore.java [hunk 10]
```diff
@@ -321,32 +281,64 @@ private Map<String, VraNgApprovalPolicy> getCurrentPoliciesOnFileSystem(Path pol
...
+		Map<String, VraNgApprovalPolicy> policies = new HashMap<>();
+		boolean includeAll = itemNames.size() == 0;
+
+		this.getAllServerContents().forEach(policy -> {
+			if (policy.getTypeId().equals(VraNgPolicyTypes.APPROVAL_POLICY_TYPE)
+					&& (includeAll || itemNames.contains(policy.getName()))) {
+				if (policies.containsKey(policy.getName())) {
+					throw new RuntimeException(
+							String.format(
+									"More than one approval policy with name '%s' already exists. While Aria supports policies with the same type and name, the build tools cannot. This is because we need to distinguish policies.",
```
Comment (VenelinBakalov) [inline common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgApprovalPolicyStore.java:315]:
```suggestion
									"More than one approval policy with name '%s' already exists. While Aria Automation supports policies with the same type and name, Build Tools for Aria does not support duplicate policy names of the same type in order to properly resolve the desired policy.",
```

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgApprovalPolicyStore.java [hunk 11]
```diff
@@ -321,32 +281,64 @@ private Map<String, VraNgApprovalPolicy> getCurrentPoliciesOnFileSystem(Path pol
...
+				logger.debug("Found policy: {}", policy.getName());
+				policies.put(policy.getName(), policy);
+			}
+		});
+
+		return policies;
+	}
+
+	/**
+	 * Sanitizes the give JSON object policy by removing properties that should not
```
Comment (VenelinBakalov) [inline common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgApprovalPolicyStore.java:328]:
```suggestion
	 * Sanitizes the given JSON object policy by removing properties that should not
```

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgApprovalPolicyStore.java [hunk 12]
```diff
@@ -321,32 +281,64 @@ private Map<String, VraNgApprovalPolicy> getCurrentPoliciesOnFileSystem(Path pol
...
+	 * be stored.
+	 *
+	 * The `projectId` must not be removed, as it controls wether a policy is
```
Comment (VenelinBakalov) [inline common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgApprovalPolicyStore.java:331]:
```suggestion
	 * The `projectId` must not be removed, as it controls whether a policy is
```

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgContentSharingPolicyStore.java [hunk 13]
```diff
@@ -324,150 +419,50 @@ private VraNgContentSharingPolicy jsonFileToVraNgContentSharingPolicy(final File
...
+		Map<String, VraNgContentSharingPolicy> policies = new HashMap<>();
+		boolean includeAll = itemNames.size() == 0;
+
+		this.getAllServerContents().forEach(policy -> {
+			if (policy.getTypeId().equals(VraNgPolicyTypes.CONTENT_SHARING_POLICY_TYPE)
+					&& (includeAll || itemNames.contains(policy.getName()))) {
+				if (policies.containsKey(policy.getName())) {
+					throw new RuntimeException(
+							String.format(
+									"More than one content sharing policy with name '%s' already exists. While Aria supports policies with the same type and name, the build tools cannot. This is because we need to distinguish policies.",
```
Comment (VenelinBakalov) [inline common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgContentSharingPolicyStore.java:439]: I would suggest the same error update as with the approval policy

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgContentSharingPolicyStore.java [hunk 14]
```diff
@@ -324,150 +419,50 @@ private VraNgContentSharingPolicy jsonFileToVraNgContentSharingPolicy(final File
...
 
-		return currentPoliciesOnFileSystem;
+		return policies;
 	}
 
 	/**
-	 * Extract content-sharing policies sub-folder absolute file system path.
-	 * 
-	 * @return the content-sharing policies sub-folder absolute file system path.
+	 * Sanitizes the give JSON object policy by removing properties that should not
```
Comment (VenelinBakalov) [inline common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgContentSharingPolicyStore.java:452]:
```suggestion
	 * Sanitizes the given JSON object policy by removing properties that should not
```

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgDeploymentLimitPolicyStore.java [hunk 15]
```diff
@@ -78,98 +107,76 @@ protected void deleteResourceById(String resId) {
...
-	@Override
-	protected List<String> getItemListFromDescriptor() {
-		if (this.vraNgPackageDescriptor.getPolicy() == null) {
-			return null;
-		} else {
-			return this.vraNgPackageDescriptor.getPolicy().getDeploymentLimit();
+		policy.setOrgId(VraNgOrganizationUtil.getOrganization(this.restClient, this.config).getId());
+
+		if (policiesOnServer.containsKey(policy.getName())) {
+			this.logger.warn("Deployment Limit policy '{}' already exists on the server. Deleting it first.",
```
Comment (pboychev-bcom) [inline common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgDeploymentLimitPolicyStore.java:157]: Not sure if we can use patch instead.
If not - what would happen if the import fails later? Should / could we restore the original policy? Maybe store the definition in memory / file and restore if the creation of the new one fails? Ideally we might want to ensure the business continuity.

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgContentSharingPolicyStore.java [hunk 16]
```diff
@@ -324,150 +419,50 @@ private VraNgContentSharingPolicy jsonFileToVraNgContentSharingPolicy(final File
...
+	 * be stored.
+	 *
+	 * The `projectId` must not be removed, as it controls wether a policy is
```
Comment (VenelinBakalov) [inline common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgContentSharingPolicyStore.java:455]:
```suggestion
	 * The `projectId` must not be removed, as it controls whether a policy is
```

**Review by pboychev-bcom — COMMENTED** [review]
Great effort, Stef, thank you so much!

There's a few comments here and there, some might trigger discussions on the tool behaviour, the comments will be applicable for multiple operations even if it's only one comment, these might require more broad discussions, mainly concerns:
- Configuration significance - no config - pull all, empty config - pull none, specific config - pull specified - do we want that, is it there already?
- Rollback type of behaviour - in cases where we delete items and create the new ones and the creation fails, how do we ensure business continuity? Re-creating the original entries? We should also consider partial state being uploaded - some policies are there, some are not, would there be business disruptions caused.

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgDeploymentLimitPolicyStore.java (hunk 15 above)
Comment (Michaelpalacce) [reply common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgDeploymentLimitPolicyStore.java:157]: So that was originally how I started implementing this, however as it turns out, there are a lot of things that are forbidden from being changed once you have the policy already in place. 

I was thinking as an alternative approach: try to update, if it fails, delete it, but at the end I went for this directly. This also is what we do with other resources.

Should I do it this way?

Comment (Michaelpalacce) [reply common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgDeploymentLimitPolicyStore.java:157]: Regarding rollback -> sounds like a good option. Perhaps we can do it in a separate task and also implement rollback for other resources that are being deleted?

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgContentSharingPolicyStore.java (hunk 8 above)
Comment (Michaelpalacce) [reply common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgContentSharingPolicyStore.java:191]: This is how it will work right now, yes 😄 

`fetchPolicies` func will do the filtering for us

File: .github/linters/sun_checks.xml [hunk 17]
```diff
@@ -180,16 +180,15 @@ https://www.oracle.com/java/technologies/javase/codeconventions-contents.html
...
+		<module name="MagicNumber" />
 		<module name="MissingSwitchDefault" />
 		<module name="MultipleVariableDeclarations" />
 		<module name="SimplifyBooleanExpression" />
 		<module name="SimplifyBooleanReturn" />
 
 		<!-- Checks for class design                         -->
 		<!-- See https://checkstyle.org/config_design.html -->
-		<!-- Uncomment later -->
-		<!-- <module name="DesignForExtension" /> -->
```
[the remark this answers is not in the document]
Comment (Michaelpalacce) [reply .github/linters/sun_checks.xml:192]: Hmm, not sure what you mean? This was something I commented out when I was doing a refactoring and I didn't want to edit a bunch of files just because I moved them (by edit I mean add documentation and stuff)

[the remark this answers is not in the document]
Comment (pboychev-bcom) [reply .github/linters/sun_checks.xml:192]: Brain malfunction, for some reason I saw a duplicated line :D

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgDeploymentLimitPolicyStore.java (hunk 15 above)
Comment (pboychev-bcom) [reply common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgDeploymentLimitPolicyStore.java:157]: Absolutely agree, let's take this for internal discussion **but** for creating a separate task for it :)
The discussion should be more broad both in terms of members having their say and the approach in the general tool behaviour, not just at specific places so we have consistency in the experience.

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgApprovalPolicyStore.java (hunk 12 above)
Comment (pboychev-bcom) [reply common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgApprovalPolicyStore.java:331]: Comment on all your notes above - I love your attention to detail <3 :D

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgDay2ActionsPolicyStore.java [hunk 18]
```diff
@@ -344,4 +288,53 @@ private VraNgDay2ActionsPolicy jsonFileToVraNgDay2ActionsPolicy(final File jsonF
...
+		Map<String, VraNgDay2ActionsPolicy> policies = new HashMap<>();
+		boolean includeAll = itemNames.size() == 0;
+
+		this.getAllServerContents().forEach(policy -> {
+			if (policy.getTypeId().equals(VraNgPolicyTypes.DAY2_ACTION_POLICY_TYPE)
+					&& (includeAll || itemNames.contains(policy.getName()))) {
+				if (policies.containsKey(policy.getName())) {
+					throw new RuntimeException(
+							String.format(
+									"More than one day two policy with name '%s' already exists. While Aria supports policies with the same type and name, the build tools cannot. This is because we need to distinguish policies.",
```
Comment (VenelinBakalov) [inline common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgDay2ActionsPolicyStore.java:311]: Same suggestion here

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgDay2ActionsPolicyStore.java [hunk 19]
```diff
@@ -344,4 +288,53 @@ private VraNgDay2ActionsPolicy jsonFileToVraNgDay2ActionsPolicy(final File jsonF
...
+				logger.debug("Found policy: {}", policy.getName());
+				policies.put(policy.getName(), policy);
+			}
+		});
+
+		return policies;
+	}
+
+	/**
+	 * Sanitizes the give JSON object policy by removing properties that should not
```
Comment (VenelinBakalov) [inline common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgDay2ActionsPolicyStore.java:324]:
```suggestion
	 * Sanitizes the given JSON object policy by removing properties that should not
```

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgDay2ActionsPolicyStore.java [hunk 20]
```diff
@@ -344,4 +288,53 @@ private VraNgDay2ActionsPolicy jsonFileToVraNgDay2ActionsPolicy(final File jsonF
...
+	 * be stored.
+	 *
+	 * The `projectId` must not be removed, as it controls wether a policy is
```
Comment (VenelinBakalov) [inline common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgDay2ActionsPolicyStore.java:327]:
```suggestion
	 * The `projectId` must not be removed, as it controls whether a policy is
```

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgDeploymentLimitPolicyStore.java [hunk 21]
```diff
@@ -340,4 +289,53 @@ private VraNgDeploymentLimitPolicy jsonFileToVraNgDeploymentLimitPolicy(final Fi
...
+		Map<String, VraNgDeploymentLimitPolicy> policies = new HashMap<>();
+		boolean includeAll = itemNames.size() == 0;
+
+		this.getAllServerContents().forEach(policy -> {
+			if (policy.getTypeId().equals(VraNgPolicyTypes.DEPLOYMENT_LIMIT_POLICY_TYPE)
+					&& (includeAll || itemNames.contains(policy.getName()))) {
+				if (policies.containsKey(policy.getName())) {
+					throw new RuntimeException(
+							String.format(
+									"More than one deployment limit policy with name '%s' already exists. While Aria supports policies with the same type and name, the build tools cannot. This is because we need to distinguish policies.",
```
Comment (VenelinBakalov) [inline common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgDeploymentLimitPolicyStore.java:312]: Same suggestion here

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgLeasePolicyStore.java [hunk 22]
```diff
@@ -307,15 +265,64 @@ private Map<String, VraNgLeasePolicy> getCurrentPoliciesOnFileSystem(Path policy
...
+		Map<String, VraNgLeasePolicy> policies = new HashMap<>();
+		boolean includeAll = itemNames.size() == 0;
+
+		this.getAllServerContents().forEach(policy -> {
+			if (policy.getTypeId().equals(VraNgPolicyTypes.LEASE_POLICY_TYPE)
+					&& (includeAll || itemNames.contains(policy.getName()))) {
+				if (policies.containsKey(policy.getName())) {
+					throw new RuntimeException(
+							String.format(
+									"More than one lease policy with name '%s' already exists. While Aria supports policies with the same type and name, the build tools cannot. This is because we need to distinguish policies.",
```
Comment (VenelinBakalov) [inline common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgLeasePolicyStore.java:299]: Same

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgLeasePolicyStore.java [hunk 23]
```diff
@@ -307,15 +265,64 @@ private Map<String, VraNgLeasePolicy> getCurrentPoliciesOnFileSystem(Path policy
...
+				logger.debug("Found policy: {}", policy.getName());
+				policies.put(policy.getName(), policy);
+			}
+		});
+
+		return policies;
+	}
+
+	/**
+	 * Sanitizes the give JSON object policy by removing properties that should not
```
Comment (VenelinBakalov) [inline common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgLeasePolicyStore.java:312]:
```suggestion
	 * Sanitizes the given JSON object policy by removing properties that should not
```

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgLeasePolicyStore.java [hunk 24]
```diff
@@ -307,15 +265,64 @@ private Map<String, VraNgLeasePolicy> getCurrentPoliciesOnFileSystem(Path policy
...
+	 * be stored.
+	 *
+	 * The `projectId` must not be removed, as it controls wether a policy is
```
Comment (VenelinBakalov) [inline common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgLeasePolicyStore.java:315]:
```suggestion
	 * The `projectId` must not be removed, as it controls whether a policy is
```

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgResourceQuotaPolicyStore.java [hunk 25]
```diff
@@ -328,15 +276,64 @@ private Map<String, VraNgResourceQuotaPolicy> getCurrentPoliciesOnFileSystem(Pat
...
+				logger.debug("Found policy: {}", policy.getName());
+				policies.put(policy.getName(), policy);
+			}
+		});
+
+		return policies;
+	}
+
+	/**
+	 * Sanitizes the give JSON object policy by removing properties that should not
```
Comment (VenelinBakalov) [inline common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgResourceQuotaPolicyStore.java:323]:
```suggestion
	 * Sanitizes the given JSON object policy by removing properties that should not
```

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgResourceQuotaPolicyStore.java [hunk 26]
```diff
@@ -328,15 +276,64 @@ private Map<String, VraNgResourceQuotaPolicy> getCurrentPoliciesOnFileSystem(Pat
...
+	 * be stored.
+	 *
+	 * The `projectId` must not be removed, as it controls wether a policy is
```
Comment (VenelinBakalov) [inline common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgResourceQuotaPolicyStore.java:326]:
```suggestion
	 * The `projectId` must not be removed, as it controls whether a policy is
```

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgApprovalPolicyStore.java (hunk 12 above)
Comment (VenelinBakalov) [reply common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgApprovalPolicyStore.java:331]: Haha maximum commitment :)

File: .github/linters/sun_checks.xml (hunk 17 above)
[the remark this answers is not in the document]
Comment (Michaelpalacce) [reply .github/linters/sun_checks.xml:192]: all good 😄

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgDeploymentLimitPolicyStore.java (hunk 15 above)
Comment (Michaelpalacce) [reply common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgDeploymentLimitPolicyStore.java:157]: Perfect, adding it to the internal roadmap

**Review by pboychev-bcom — APPROVED** [review]

File: common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgDeploymentLimitPolicyStore.java (hunk 15 above)
Comment (VenelinBakalov) [reply common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/store/VraNgDeploymentLimitPolicyStore.java:157]: We will create an issue for this improvement and hopefully soon implement it. I will leave a link here.
